name: Deploy Pages
on:
  push:
    branches: [main]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@39370e3970a6d0505907c07dd2336c147af158f7 # v4.1.0
        with:
          node-version: '22'
          cache: npm
      - run: npm ci
      - run: npm run validate:data
      - run: npm run build
      - uses: actions/configure-pages@983d7736a752c995a027155b1c2f179d9715ed # v5
      - uses: actions/upload-pages-artifact@56afc609e742026a2b238fcc214ba48a79bc807 # v3
        with:
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@d76988a129c8826d87e5d664f04460facbb1 # v4
        id: deployment
